version: 2.1

orbs: 
  python: circleci/python@2.0.3
  docker: circleci/docker@2.1.2

jobs:
  build_test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run Tests
          command: pytest
      - run:
          name : Run Linting
          command: flake8
  build_push:
    docker: 
      - image: cimg/python:3.10
    steps:
      - checkout
      - setup_remote_docker
      - docker/check


workflows:
  build_test_deploy:
    jobs:
      - build_test:
          filters:
            branches:
              only: master
      - build_push:
          requires:
            - build_test
          filters:
            branches:
              only: master

